packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@firebase/util': true
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

catalog:
  '@types/node': ^25.9.3
  '@typescript-eslint/eslint-plugin': ^8.61.0
  '@typescript-eslint/parser': ^8.61.0
  eslint: ^10.4.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-i18next: ^6.1.4
  eslint-plugin-prettier: ^5.5.6
  prettier: ^3.8.4
  typescript: ^6.0.3
  '@vitest/coverage-v8': ^4.1.8
  vitest: ^4.1.8
minimumReleaseAgeExclude:
  - '@img/sharp-darwin-arm64@0.35.0'
  - '@img/sharp-darwin-x64@0.35.0'
  - '@img/sharp-freebsd-wasm32@0.35.0'
  - '@img/sharp-libvips-darwin-arm64@1.3.0'
  - '@img/sharp-libvips-darwin-x64@1.3.0'
  - '@img/sharp-libvips-linux-arm64@1.3.0'
  - '@img/sharp-libvips-linux-arm@1.3.0'
  - '@img/sharp-libvips-linux-ppc64@1.3.0'
  - '@img/sharp-libvips-linux-riscv64@1.3.0'
  - '@img/sharp-libvips-linux-s390x@1.3.0'
  - '@img/sharp-libvips-linux-x64@1.3.0'
  - '@img/sharp-libvips-linuxmusl-arm64@1.3.0'
  - '@img/sharp-libvips-linuxmusl-x64@1.3.0'
  - '@img/sharp-linux-arm64@0.35.0'
  - '@img/sharp-linux-arm@0.35.0'
  - '@img/sharp-linux-ppc64@0.35.0'
  - '@img/sharp-linux-riscv64@0.35.0'
  - '@img/sharp-linux-s390x@0.35.0'
  - '@img/sharp-linux-x64@0.35.0'
  - '@img/sharp-linuxmusl-arm64@0.35.0'
  - '@img/sharp-linuxmusl-x64@0.35.0'
  - '@img/sharp-wasm32@0.35.0'
  - '@img/sharp-webcontainers-wasm32@0.35.0'
  - '@img/sharp-win32-arm64@0.35.0'
  - '@img/sharp-win32-ia32@0.35.0'
  - '@img/sharp-win32-x64@0.35.0'
  - '@turbo/darwin-64@2.9.18'
  - '@turbo/darwin-arm64@2.9.18'
  - '@turbo/linux-64@2.9.18'
  - '@turbo/linux-arm64@2.9.18'
  - '@turbo/windows-64@2.9.18'
  - '@turbo/windows-arm64@2.9.18'
  - turbo@2.9.18
  - '@types/node@25.9.3'
  - sharp@0.35.0
overrides:
  '@grpc/grpc-js': '>=1.14.4'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  axios@<1.15.0: '>=1.15.0'
  cross-spawn: '>=6.0.6'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@<5.7.0: '>=5.7.0'
  file-type@>=13.0.0 <21.3.1: '>=21.3.1'
  form-data@<2.5.4: '>=2.5.4'
  glob: '>=10.5.0'
  hono: '>=4.12.21'
  lodash: '>=4.18.0'
  path-to-regexp: '>=8.4.0'
  picomatch: '>=4.0.4'
  postcss@<8.5.10: '>=8.5.10'
  protobufjs@<7.5.5: '>=7.5.5'
  qs@<6.14.1: '>=6.14.1'
  test-exclude: '>=8.0.0'
  tough-cookie@<4.1.3: '>=4.1.3'
  uuid@<14.0.0: '>=14.0.0'
