import { Injectable, Logger, ServiceUnavailableException } from '@nestjs/common';
import { createHash } from 'crypto';
import type { FeedbackResponseDto } from '@/modules/feedback/dto/feedback-response.dto';

interface GitHubIssueResponse {
  html_url: string;
  number: number;
  node_id: string;
}

interface GraphQLResponse<T> {
  data?: T;
  errors?: Array<{ message: string }>;
}

export interface FeedbackContext {
  currentPage?: string;
  userAgent?: string;
  viewportSize?: string;
  language?: string;
}

@Injectable()
export class FeedbackService {
  private readonly logger = new Logger(FeedbackService.name);
  private projectNodeId: string | null = null;

  async createFeedback(
    userId: string,
    comment: string,
    context?: FeedbackContext,
  ): Promise<FeedbackResponseDto> {
    const sanitized = this.sanitize(comment);
    const anonymizedId = createHash('sha256').update(userId).digest('hex').slice(0, 8);
    const timestamp = new Date().toISOString();

    const title = `[User Feedback] ${timestamp.split('T')[0]}`;
    const body = this.buildIssueBody(anonymizedId, timestamp, sanitized, context);

    const { issueUrl, nodeId } = await this.callGitHubApi(title, body);

    await this.addIssueToProject(nodeId).catch((err: unknown) => {
      this.logger.warn(
        'Failed to add issue to project',
        err instanceof Error ? err.message : String(err),
      );
    });

    return { issueUrl };
  }

  sanitize(text: string): string {
    return text
      .replace(/<[^>]*>/g, '')
      .replace(/\s+/g, ' ')
      .trim();
  }

  private buildIssueBody(
    anonymizedId: string,
    timestamp: string,
    comment: string,
    context?: FeedbackContext,
  ): string {
    const lines = [
      '## User Feedback',
      '',
      `**Submitted at:** ${timestamp}`,
      `**User ID (anonymized):** \`${anonymizedId}\``,
      '',
      '---',
      '',
      comment,
    ];

    if (context && Object.values(context).some(Boolean)) {
      lines.push('', '---', '', '## Context', '');
      lines.push('| Field | Value |');
      lines.push('|-------|-------|');
      if (context.currentPage) lines.push(`| Page | \`${context.currentPage}\` |`);
      if (context.language) lines.push(`| Language | ${context.language} |`);
      if (context.viewportSize) lines.push(`| Viewport | ${context.viewportSize} |`);
      if (context.userAgent) lines.push(`| User Agent | ${context.userAgent} |`);
    }

    lines.push(
      '',
      '---',
      '',
      '*This issue was automatically generated by the Chamuco Travel feedback system.*',
    );

    return lines.join('\n');
  }

  private async callGitHubApi(
    title: string,
    body: string,
  ): Promise<{ issueUrl: string; nodeId: string }> {
    const token = process.env.GITHUB_TOKEN;
    const owner = process.env.GITHUB_REPO_OWNER;
    const repo = process.env.GITHUB_REPO_NAME;

    const url = `https://api.github.com/repos/${owner}/${repo}/issues`;

    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
          'Content-Type': 'application/json',
          'X-GitHub-Api-Version': '2022-11-28',
        },
        body: JSON.stringify({ title, body, labels: ['user-feedback'] }),
      });

      if (!res.ok) {
        const text = await res.text();
        this.logger.error(`GitHub API responded ${res.status.toString()}: ${text}`);
        throw new ServiceUnavailableException('Failed to submit feedback. Please try again.');
      }

      const data = (await res.json()) as GitHubIssueResponse;
      return { issueUrl: data.html_url, nodeId: data.node_id };
    } catch (err) {
      if (err instanceof ServiceUnavailableException) throw err;
      this.logger.error('GitHub API call failed', err instanceof Error ? err.message : String(err));
      throw new ServiceUnavailableException('Failed to submit feedback. Please try again.');
    }
  }

  private async fetchProjectNodeId(): Promise<string | null> {
    if (this.projectNodeId) return this.projectNodeId;

    const projectNumber = process.env.GITHUB_PROJECT_NUMBER;
    const owner = process.env.GITHUB_REPO_OWNER;
    const token = process.env.GITHUB_TOKEN;

    if (!projectNumber || !owner || !token) return null;

    const query = `
      query($login: String!, $number: Int!) {
        user(login: $login) {
          projectV2(number: $number) { id }
        }
      }
    `;

    const res = await fetch('https://api.github.com/graphql', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({
        query,
        variables: { login: owner, number: parseInt(projectNumber, 10) },
      }),
    });

    if (!res.ok) return null;

    const result = (await res.json()) as GraphQLResponse<{ user: { projectV2: { id: string } } }>;
    const id = result.data?.user?.projectV2?.id ?? null;
    if (id) this.projectNodeId = id;
    return id;
  }

  private async addIssueToProject(issueNodeId: string): Promise<void> {
    const projectNodeId = await this.fetchProjectNodeId();
    if (!projectNodeId) return;

    const token = process.env.GITHUB_TOKEN;
    const mutation = `
      mutation($projectId: ID!, $contentId: ID!) {
        addProjectV2ItemById(input: { projectId: $projectId, contentId: $contentId }) {
          item { id }
        }
      }
    `;

    const res = await fetch('https://api.github.com/graphql', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({
        query: mutation,
        variables: { projectId: projectNodeId, contentId: issueNodeId },
      }),
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(`GitHub GraphQL responded ${res.status.toString()}: ${text}`);
    }

    const result = (await res.json()) as GraphQLResponse<{
      addProjectV2ItemById: { item: { id: string } };
    }>;
    if (result.errors?.length) {
      throw new Error(result.errors.map((e) => e.message).join(', '));
    }
  }
}
