export enum ExportField {
  DISPLAY_NAME = 'displayName',
  USERNAME = 'username',
  FIRST_NAME = 'firstName',
  LAST_NAME = 'lastName',
  EMAIL = 'email',
  PHONE = 'phone',
  DATE_OF_BIRTH = 'dateOfBirth',
  HOME_COUNTRY = 'homeCountry',
  HOME_CITY = 'homeCity',
  NATIONALITY = 'nationality',
  NATIONAL_ID_NUMBER = 'nationalIdNumber',
  PASSPORT_NUMBER = 'passportNumber',
  PASSPORT_EXPIRY = 'passportExpiry',
  BLOOD_TYPE = 'bloodType',
  DIETARY_PREFERENCE = 'dietaryPreference',
  DIETARY_NOTES = 'dietaryNotes',
  MEDICAL_NOTES = 'generalMedicalNotes',
  EMERGENCY_CONTACT = 'emergencyContact',
  ROLE = 'role',
  STATUS = 'status',
  CONFIRMED_AT = 'confirmedAt',
  IS_TRAVELER = 'isTraveler',
}
