export enum MedicalConditionType {
  DIABETES = 'DIABETES',
  EPILEPSY = 'EPILEPSY',
  SEVERE_ALLERGY_EPIPEN = 'SEVERE_ALLERGY_EPIPEN',
  ASTHMA = 'ASTHMA',
  HEART_CONDITION = 'HEART_CONDITION',
  HYPERTENSION = 'HYPERTENSION',
  BLOOD_CLOTTING_DISORDER = 'BLOOD_CLOTTING_DISORDER',
  IMMUNODEFICIENCY = 'IMMUNODEFICIENCY',
  MENTAL_HEALTH_CONDITION = 'MENTAL_HEALTH_CONDITION',
  OTHER = 'OTHER',
}
