export enum NotificationType {
  GROUP_INVITATION = 'GROUP_INVITATION',
  GROUP_INVITATION_ACCEPTED = 'GROUP_INVITATION_ACCEPTED',
  GROUP_JOIN_ACCEPTED = 'GROUP_JOIN_ACCEPTED',
  GROUP_ANNOUNCEMENT = 'GROUP_ANNOUNCEMENT',
  TRIP_INVITATION = 'TRIP_INVITATION',
  TRIP_ANNOUNCEMENT = 'TRIP_ANNOUNCEMENT',
  TRIP_KEY_DATE_REMINDER = 'TRIP_KEY_DATE_REMINDER',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
  PASSPORT_EXPIRING_SOON = 'PASSPORT_EXPIRING_SOON',
  PASSPORT_EXPIRED = 'PASSPORT_EXPIRED',
  ACHIEVEMENT_UNLOCKED = 'ACHIEVEMENT_UNLOCKED',
}
