const FALLBACK_TIMEZONES = [
  'UTC',
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Toronto',
  'America/Vancouver',
  'America/Bogota',
  'America/Lima',
  'America/Caracas',
  'America/La_Paz',
  'America/Santiago',
  'America/Argentina/Buenos_Aires',
  'America/Sao_Paulo',
  'America/Mexico_City',
  'America/Costa_Rica',
  'America/Guatemala',
  'America/Tegucigalpa',
  'America/El_Salvador',
  'America/Managua',
  'America/Panama',
  'America/Santo_Domingo',
  'America/Havana',
  'America/Puerto_Rico',
  'America/Guayaquil',
  'America/Asuncion',
  'America/Montevideo',
  'Europe/London',
  'Europe/Madrid',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Rome',
  'Europe/Lisbon',
  'Europe/Amsterdam',
  'Europe/Brussels',
  'Europe/Zurich',
  'Europe/Stockholm',
  'Europe/Warsaw',
  'Europe/Kiev',
  'Europe/Moscow',
  'Asia/Dubai',
  'Asia/Kolkata',
  'Asia/Dhaka',
  'Asia/Bangkok',
  'Asia/Singapore',
  'Asia/Shanghai',
  'Asia/Tokyo',
  'Asia/Seoul',
  'Asia/Jakarta',
  'Asia/Karachi',
  'Asia/Riyadh',
  'Asia/Tehran',
  'Africa/Cairo',
  'Africa/Lagos',
  'Africa/Nairobi',
  'Africa/Johannesburg',
  'Australia/Sydney',
  'Australia/Melbourne',
  'Australia/Brisbane',
  'Australia/Perth',
  'Pacific/Auckland',
  'Pacific/Honolulu',
  'Pacific/Fiji',
];

export const TIMEZONES: readonly string[] = (() => {
  try {
    return Intl.supportedValuesOf('timeZone');
  } catch {
    return FALLBACK_TIMEZONES;
  }
})();

export const COUNTRY_TIMEZONE: Record<string, string> = {
  AE: 'Asia/Dubai',
  AR: 'America/Argentina/Buenos_Aires',
  AU: 'Australia/Sydney',
  BE: 'Europe/Brussels',
  BO: 'America/La_Paz',
  BR: 'America/Sao_Paulo',
  CA: 'America/Toronto',
  CH: 'Europe/Zurich',
  CL: 'America/Santiago',
  CN: 'Asia/Shanghai',
  CO: 'America/Bogota',
  CR: 'America/Costa_Rica',
  CU: 'America/Havana',
  DE: 'Europe/Berlin',
  DO: 'America/Santo_Domingo',
  EC: 'America/Guayaquil',
  EG: 'Africa/Cairo',
  ES: 'Europe/Madrid',
  FR: 'Europe/Paris',
  GB: 'Europe/London',
  GT: 'America/Guatemala',
  HN: 'America/Tegucigalpa',
  ID: 'Asia/Jakarta',
  IN: 'Asia/Kolkata',
  IT: 'Europe/Rome',
  JP: 'Asia/Tokyo',
  KE: 'Africa/Nairobi',
  KR: 'Asia/Seoul',
  MX: 'America/Mexico_City',
  NG: 'Africa/Lagos',
  NI: 'America/Managua',
  NL: 'Europe/Amsterdam',
  NZ: 'Pacific/Auckland',
  PA: 'America/Panama',
  PE: 'America/Lima',
  PH: 'Asia/Manila',
  PK: 'Asia/Karachi',
  PL: 'Europe/Warsaw',
  PR: 'America/Puerto_Rico',
  PT: 'Europe/Lisbon',
  PY: 'America/Asuncion',
  RU: 'Europe/Moscow',
  SA: 'Asia/Riyadh',
  SE: 'Europe/Stockholm',
  SG: 'Asia/Singapore',
  SV: 'America/El_Salvador',
  TH: 'Asia/Bangkok',
  TR: 'Europe/Istanbul',
  UA: 'Europe/Kiev',
  US: 'America/New_York',
  UY: 'America/Montevideo',
  VE: 'America/Caracas',
  ZA: 'Africa/Johannesburg',
};

export function formatTimezoneLabel(tz: string): string {
  try {
    const offset =
      new Intl.DateTimeFormat('en', {
        timeZone: tz,
        timeZoneName: 'shortOffset',
      })
        .formatToParts(new Date())
        .find((p) => p.type === 'timeZoneName')?.value ?? '';
    return `${tz.replace(/_/g, ' ')} ${offset}`;
  } catch {
    return tz;
  }
}
